version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          
models:
  - name: stg_order_items
    columns:
      - name: order_items_id
        tests:
          - not_null
          - unique
          
models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique